SELECT  SYSDATE,
        TO_CHAR(SYSDATE, 'DD')                               AS "DD",
        TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=KOREAN')   AS "KOREAN",
        TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=JAPANESE') AS "JAPANESE",
        TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH')  AS "ENGLISH",
        TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH_MONTH",
        TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=GERMAN')   AS "GERMAN"
FROM dual
;