-- CTAS로 DEPT_TCL 생성
CREATE TABLE dept_tcl
AS 
SELECT *
FROM dept
;
SELECT * FROM dept_tcl;

-- DEPT_TCL DML 작업
-- INSERT
INSERT INTO dept_tcl VALUES(50,'DATABASE','SEOUL');
-- UPDATE
UPDATE dept_tcl SET loc = 'BUSAN'
 WHERE deptno = 40;

-- DELETE
DELETE FROM dept_tcl WHERE dname = 'RESEARCH';

-- SELECT 확인
SELECT * FROM dept_tcl;

--10	ACCOUNTING	NEW YORK
--30	SALES	    CHICAGO
--40	OPERATIONS	BUSAN
--50	DATABASE	SEOUL

-- ROLLBACK : DML 작업들이 취소 되었는지 확인.
-- 트랜잭션 취소
ROLLBACK;

--10	ACCOUNTING	NEW YORK
--20	RESEARCH	DALLAS
--30	SALES	    CHICAGO
--40	OPERATIONS	BOSTON